# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7a78770a8c1a685384eb23768e797b18d02e758c16680222df329254b48333bc7beca68bef2e697eb04e2551540d4397c8cf957606cd33921ce38150a45dbb1

test:
  secret_key_base: f21dfd298dbb39a9307f64f558ee7d061150f7b6f0a2bd177b8398e3fd8d0b4fa22b5e8e92149736d4cd2af59aef479e0aa415fb496bd6a0c9f4eef543723e71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
